### ISSUE TITLE
Different file types into different stores

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/tac_stores_es#1]
The `.rep` files need to go into an index called `States` - this index stores the current state of a platform (ship)

The `.dsf` files need to go into an index called `Contacts` - this index stores the measurement of some other contact (another ship)

If document schemas are needed for the indexes, I've produced some here:
![image](https://docs.google.com/drawings/d/e/2PACX-1vRHK8jvEsS7oltGP41t7i3DEkuNXQRTpQHzMNYoTr4ZWmXns0J7d58kJV1ClQJkwMTJ2bBz1RUlJADY/pub?w=742&h=533)

**Comment by AlexKhl** [comment]
Problem solved. It could be tested.
